### ISSUE TITLE
Update pypy package

### ISSUE THREAD

**Issue by mon** [zeehio/parmap#10]
I'd love to use the new parmap_progress feature, all nice and integrated with pip instead of manually installing. Could the package be updated to reflect the repo?

**Comment by zeehio** [comment]
Done! 👍 Now you have parmap 1.4.0 both in pypi and conda.

Please remember that parmap requires tqdm in order to show the progress bar. As it is an extra dependency (not required), it may not be automatically installed when doing `pip install parmap` please make sure tqdm is installed if you want to use it (`pip install parmap tqdm`).

I will close the issue as I do not need to do anything else, but please feel free to add any comment if you have any related problem. I would appreciate if you entered in https://github.com/zeehio/parmap/issues/11 and dropped a message about what are you using `parmap` for, if you want 😃 

Best!

Sergio
