### ISSUE TITLE
Immortal processes

### ISSUE THREAD

**Issue by oopcode** [zeehio/parmap#4]
Hi, thanks for the nice tool. I found something that (I believe) is an issue (or just my ignorance).

I use a small wrapper around the `starmap()` function inside a handler for `SIGALRM`.

The wrapper looks like this:

``` python

def execute_parallel(callback, callback_args, workers=4):
    """
    Docstring...
    """
    if not isinstance(callback_args, collections.Iterable):
        raise Exception(EXIT_NOT_ITERABLE)

    pool = Pool(processes=workers)
    return starmap(callback, callback_args, pool=pool)
    
```

and the handler is set up as follows:

``` python

def do_stuff(sig, frame):
        # some code that calls execute_parallel()
        # and collects the result

    signal.signal(signal.SIGALRM, do_stuff)
    signal.setitimer(signal.ITIMER_REAL, 0.1, interval)

```

The problem is that although my wrapper actually returns the desired result, none of the processes created for the handler ever get killed. Those processes are created infinitely in my case, which is a problem (memory, etc.), so I sort of fixed this by adding a .`terminate()` call on the pool (see below). But I'm not sure it's cool.

``` python
def execute_parallel(callback, callback_args, workers=4):
    """
    Docstring...
    """
    if not isinstance(callback_args, collections.Iterable):
        raise Exception(EXIT_NOT_ITERABLE)

    pool = Pool(processes=workers)
    product = starmap(callback, callback_args, pool=pool)
    pool.terminate()

    return product

```

Maybe it's not an issue at all; sorry then.

**Comment by zeehio** [comment]
Hi,
Thanks for reporting the issue :-)

I decided that parmap would close only the pools that it opened, so if you choose to create a pool you have to be responsible for closing it. Take a look at: https://github.com/zeehio/parmap/blob/master/parmap.py#L170 to see how and when parmap closes its own pools. See how `close_pool == True` only when parmap has created the pool.

This approach makes sense to me because some users may want to reuse the pools in multiple calls. They may want to do this to avoid the overhead of creating and closing python processes all the time. Moreover, I think it is good practice to not close resources allocated by others, so each developer is responsible for their "own" objects.

Regarding how to finish the pools, I believe that `pool.close()` followed by `pool.join()` is safer than `pool.terminate()` in a general case. `pool.terminate()` may end up corrupting the pipe of the associated process according to https://docs.python.org/dev/library/multiprocessing.html#multiprocessing.Process.terminate

I close the issue because I don't think it needs fixing but please feel free to reply and/or reopen :+1:

**Comment by oopcode** [comment]
Thank you for the answer! Sure, I will use `pool.close()` followed by `pool.join()`.  :-)
